
name: Go AoC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      AOC_SESSION:
        description: 'AoC Session Cookie'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build test
      run: go build -o aoc_2023 main.go

    - name: Archive solution binary
      uses: actions/upload-artifact@v3
      with:
        name: aoc_2023
        path: aoc_2023

    - name: Run test
      env: # Or as an environment variable
        AOC_SECRET: ${{ inputs.AOC_SESSION != '' && inputs.AOC_SESSION || secrets.AOC_SESSION }}
      run: go run main.go --all
